syntax = "proto3";

package voxel;

message Vec3{
    float x = 1;
    float y = 2;
    float z = 3;
}

message Observation{
    repeated float heights = 1;
    repeated bool valids = 2;

    // Both heights and valids should be the same size of: map_x_sz * map_z_sz
    int32 map_x_sz = 3;
    int32 map_z_sz = 4;

    Vec3 position = 5;
    Vec3 velocity = 6;
    bool is_grounded = 7;
}

message ResetRequest{
    uint32 seed = 1;
}

message ResetResponse{
    Observation obs = 1;
}

message StepRequest{
    float dir_x = 1;
    float dir_z = 2;
    bool jump = 3;
}

message StepResponse{
    Observation obs = 1;
    float reward = 2;
    bool terminated = 3;
    bool truncated = 4;
}

service SimulationService {
    rpc Reset(ResetRequest) returns (ResetResponse);
    rpc Step(StepRequest) returns (StepResponse);
}